modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/neila-a/HiddenWorldBorder/issues"
license = "GNU GPL 3.0"

[[mods]]
modId = "hiddenworldborder"
version = "${version}"
displayName = "Hidden World Border"
authors = "Neila"
description = """
Hide the world border.
"""
logoFile = "assets/hiddenworldborder/icon.png"
displayURL = "https://github.com/neila-a/HiddenWorldBorder"

[[dependencies.hiddenworldborder]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hiddenworldborder]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,)"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "hiddenworldborder.mixins.json"
